# Generated by Django 5.0.14 on 2026-09-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='控件名称（来自 manifest.json）', max_length=128)),
                ('widget_type', models.CharField(help_text='控件类型标识（来自 manifest.json type）', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='控件说明')),
                ('version', models.CharField(default='1.0.0', help_text='版本号', max_length=32)),
                ('manifest', models.JSONField(default=dict, help_text='manifest.json 原始内容')),
                ('file_path', models.CharField(help_text='zip 文件相对路径', max_length=512)),
                ('extract_dir', models.CharField(help_text='解压目录相对路径', max_length=512)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'widget_packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
