# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('labor_count', models.IntegerField()),
                ('max_per_year', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='competitions.competition')),
            ],
            options={
                'db_table': 'production_lines',
                'indexes': [models.Index(fields=['competition', 'updated_at'], name='production__competi_1bb4c0_idx')],
                'unique_together': {('competition', 'name')},
            },
        ),
    ]
