# Generated by Django 5.0.14 on 2026-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_lines', '0003_alter_productionline_max_per_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='max_per_year',
            field=models.DecimalField(decimal_places=4, max_digits=60),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=60),
        ),
    ]
