# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer_demands', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerdemand',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer_demands', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='consumerdemand',
            index=models.Index(fields=['competition', 'region'], name='consumer_de_competi_02c619_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerdemand',
            index=models.Index(fields=['competition', 'updated_at'], name='consumer_de_competi_fb51d8_idx'),
        ),
    ]
