# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('total_shares', models.FloatField()),
                ('init_net_profit', models.FloatField()),
                ('industry_pe', models.FloatField()),
                ('current_carbon', models.FloatField()),
                ('industry_avg_carbon', models.FloatField()),
                ('happiness', models.FloatField()),
                ('carbon_field_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('happiness_field_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_avg_carbon_refs', models.CharField(blank=True, max_length=1024, null=True)),
                ('pb_company_id', models.IntegerField(blank=True, null=True)),
                ('pb_field_id', models.IntegerField(blank=True, null=True)),
                ('pb_random', models.FloatField(blank=True, null=True)),
                ('init_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('round', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='companies.company')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='competitions.competition')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='StockCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('change_pct', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_candles', to='competitions.competition')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='stock.stock')),
            ],
            options={
                'db_table': 'stock_candles',
            },
        ),
        migrations.CreateModel(
            name='StockFundsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_type', models.CharField(choices=[('COMPANY', 'COMPANY'), ('USER', 'USER')], max_length=16)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('cash_balance', models.FloatField(default=1000000)),
                ('bind_field_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_funds_accounts', to='competitions.competition')),
            ],
            options={
                'db_table': 'stock_funds_accounts',
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='competitions.competition')),
                ('funds_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stock.stockfundsaccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stock.stock')),
            ],
            options={
                'db_table': 'stock_holdings',
            },
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=8)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FILLED', 'FILLED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=16)),
                ('round', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_orders', to='competitions.competition')),
                ('funds_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stock.stockfundsaccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stock.stock')),
            ],
            options={
                'db_table': 'stock_orders',
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['competition', 'updated_at'], name='stocks_competi_0f4540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('competition', 'code')},
        ),
        migrations.AddIndex(
            model_name='stockcandle',
            index=models.Index(fields=['competition', 'updated_at'], name='stock_candl_competi_68c963_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcandle',
            unique_together={('stock', 'round')},
        ),
        migrations.AddIndex(
            model_name='stockfundsaccount',
            index=models.Index(fields=['competition', 'updated_at'], name='stock_funds_competi_e8f605_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockfundsaccount',
            unique_together={('competition', 'name')},
        ),
        migrations.AddIndex(
            model_name='stockholding',
            index=models.Index(fields=['competition', 'updated_at'], name='stock_holdi_competi_303b18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together={('funds_account', 'stock')},
        ),
        migrations.AddIndex(
            model_name='stockorder',
            index=models.Index(fields=['competition', 'stock', 'round', 'status'], name='stock_order_competi_d7c94c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockorder',
            index=models.Index(fields=['competition', 'updated_at'], name='stock_order_competi_9e85dc_idx'),
        ),
    ]
