# Generated by Django 5.0.14 on 2026-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('stock', '0005_stockcandle_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='shares',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=60),
        ),
        migrations.AddConstraint(
            model_name='stockholding',
            constraint=models.CheckConstraint(check=models.Q(('shares__gte', 0)), name='stock_holding_shares_non_negative'),
        ),
    ]
