# Generated by Django 5.0.6 on 2026-08-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('COMPETITION_ADMIN', 'COMPETITION_ADMIN'), ('PLAYER', 'PLAYER')], default='PLAYER', max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('company_scopes', models.TextField(blank=True, null=True)),
                ('view_company_scopes', models.TextField(blank=True, null=True)),
                ('contract_view_company_scopes', models.TextField(blank=True, null=True)),
                ('stock_company_scopes', models.TextField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('token_version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='competitions.competition')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['competition', 'updated_at'], name='users_competi_43c99c_idx')],
            },
        ),
    ]
