# Generated by Django 5.0.6 on 2026-08-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_version',
            field=models.IntegerField(default=0),
        ),
    ]
