# Generated by Django 5.0.14 on 2026-09-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
