# Generated by Django 5.0.14 on 2026-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuels', '0003_alter_fuel_price_per_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=4, max_digits=60),
        ),
    ]
