# Generated by Django 5.0.6 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('write', 'write'), ('error', 'error')], default='write', max_length=16)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=128, null=True)),
                ('action', models.CharField(max_length=128)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('record_id', models.CharField(blank=True, max_length=64, null=True)),
                ('competition_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_summary', models.CharField(blank=True, max_length=512, null=True)),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['kind', 'created_at'], name='audit_log_kind_2f0b1e_idx'), models.Index(fields=['operator_id', 'created_at'], name='audit_log_operato_b284e5_idx'), models.Index(fields=['model', 'created_at'], name='audit_log_model_1ee79a_idx'), models.Index(fields=['request_id'], name='audit_log_request_a46c86_idx')],
            },
        ),
    ]
