# Generated by Django 5.0.14 on 2026-09-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
