# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('tier', models.IntegerField(default=0)),
                ('research_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_nodes', to='competitions.competition')),
            ],
            options={
                'db_table': 'tech_nodes',
            },
        ),
        migrations.CreateModel(
            name='TechPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='tech_tree.technode')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='tech_tree.technode')),
            ],
            options={
                'db_table': 'tech_prerequisites',
            },
        ),
        migrations.AddIndex(
            model_name='technode',
            index=models.Index(fields=['competition', 'updated_at'], name='tech_nodes_competi_0477e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technode',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='techprerequisite',
            unique_together={('node', 'prerequisite')},
        ),
    ]
