# Generated by Django 5.0.6 on 2026-08-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('carbon_emission_coefficient', models.FloatField()),
                ('node_prices', models.TextField(default='{}')),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('SPECIAL', 'SPECIAL')], default='NORMAL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='competitions.competition')),
            ],
            options={
                'db_table': 'materials',
                'indexes': [models.Index(fields=['competition', 'updated_at'], name='materials_competi_268065_idx')],
                'unique_together': {('competition', 'name')},
            },
        ),
    ]
