# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('industry_types', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='regions.region'),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='industry_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='industry_types.industryfield'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['competition', 'updated_at'], name='companies_competi_62b974_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfieldvalue',
            index=models.Index(fields=['version'], name='company_fie_version_4db5e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfieldvalue',
            unique_together={('company', 'industry_field')},
        ),
    ]
