# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('fuels', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fuel_consumption_per_km', models.FloatField()),
                ('max_cargo', models.FloatField()),
                ('price', models.FloatField()),
                ('carbon_emission', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='competitions.competition')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fuels.fuel')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehiclePathType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='maps.pathtype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_path_types', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_path_types',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['competition', 'updated_at'], name='vehicles_competi_c92fee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclepathtype',
            unique_together={('vehicle', 'path_type')},
        ),
    ]
