# Generated by manual edit 2026-10-10 — split Vehicle.max_cargo into three cargo-type fields.

import django.db.models.deletion
from django.db import migrations, models


def copy_cargo_to_three(apps, schema_editor):
    """把旧 max_cargo 复制到三个新字段（保存已有数据，用户随后手动修正）。"""
    Vehicle = apps.get_model("vehicles", "Vehicle")
    # 大批量更新用 update()；已有数据极少（≤50 家公司 × ≤10 种载具），
    # 直接全量 update 更简单可靠。
    Vehicle.objects.filter().update(
        max_material_cargo=models.F("max_cargo"),
        max_part_cargo=models.F("max_cargo"),
        max_product_cargo=models.F("max_cargo"),
    )


def reverse_copy(apps, schema_editor):
    """反向迁移：max_cargo 取三个字段中的最大值（保守近似；原表已删列，无法精确恢复）。"""
    Vehicle = apps.get_model("vehicles", "Vehicle")
    for v in Vehicle.objects.all():
        old = max(v.max_material_cargo or 0, v.max_part_cargo or 0, v.max_product_cargo or 0)
        # max_cargo 列已不存在，此方法无法写入——反向迁移需完整重建原表，不再支持。
        # 若确需回滚，请在应用迁移前备份数据。
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_alter_vehicle_price"),
    ]

    operations = [
        # ① 先加新列（默认 0，用户随后修正）
        migrations.AddField(
            model_name="vehicle",
            name="max_material_cargo",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="max_part_cargo",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="max_product_cargo",
            field=models.FloatField(default=0),
        ),
        # ② 把旧 max_cargo 的值复制到三个新列（F 表达式，单条 UPDATE，无 Python 循环）
        migrations.RunPython(copy_cargo_to_three, reverse_copy),
        # ③ 删旧列
        migrations.RemoveField(
            model_name="vehicle",
            name="max_cargo",
        ),
    ]