# Generated by Django 5.0.14 on 2026-09-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='版本号，如 1.4.0', max_length=32)),
                ('title', models.CharField(help_text='公告标题', max_length=255)),
                ('date', models.CharField(help_text='发布日期 YYYY-MM-DD（展示用）', max_length=16)),
                ('content', models.TextField(help_text='公告正文，支持受信任 HTML 片段')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用（停用后前端不展示）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
