# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('overview_cards', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='competitions.competition')),
            ],
            options={
                'db_table': 'regions',
                'indexes': [models.Index(fields=['competition', 'updated_at'], name='regions_competi_007e09_idx')],
                'unique_together': {('competition', 'name')},
            },
        ),
    ]
