# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapNodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_node_types', to='competitions.competition')),
            ],
            options={
                'db_table': 'map_node_types',
            },
        ),
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('region', models.CharField(default='', max_length=128)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_nodes', to='competitions.competition')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='maps.mapnodetype')),
            ],
            options={
                'db_table': 'map_nodes',
            },
        ),
        migrations.CreateModel(
            name='PathType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_types', to='competitions.competition')),
            ],
            options={
                'db_table': 'path_types',
            },
        ),
        migrations.CreateModel(
            name='MapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_edges', to='competitions.competition')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='maps.mapnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='maps.mapnode')),
                ('path_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='maps.pathtype')),
            ],
            options={
                'db_table': 'map_edges',
            },
        ),
        migrations.AddIndex(
            model_name='mapnodetype',
            index=models.Index(fields=['competition', 'updated_at'], name='map_node_ty_competi_7674e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapnodetype',
            unique_together={('competition', 'name')},
        ),
        migrations.AddIndex(
            model_name='mapnode',
            index=models.Index(fields=['competition', 'updated_at'], name='map_nodes_competi_bc2c4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapnode',
            unique_together={('competition', 'name')},
        ),
        migrations.AddIndex(
            model_name='pathtype',
            index=models.Index(fields=['competition', 'updated_at'], name='path_types_competi_685c36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pathtype',
            unique_together={('competition', 'name')},
        ),
        migrations.AddIndex(
            model_name='mapedge',
            index=models.Index(fields=['competition', 'updated_at'], name='map_edges_competi_45924e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapedge',
            unique_together={('from_node', 'to_node')},
        ),
    ]
