# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'industry_types',
            },
        ),
        migrations.CreateModel(
            name='IndustryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_key', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('STRING', 'STRING'), ('NUMBER', 'NUMBER'), ('BOOLEAN', 'BOOLEAN'), ('DICTIONARY', 'DICTIONARY'), ('LIST', 'LIST')], default='NUMBER', max_length=16)),
                ('config', models.TextField(default='{}')),
                ('default_value', models.TextField(blank=True, null=True)),
                ('is_calculated', models.BooleanField(default=False)),
                ('calc_graph', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('timer_enabled', models.BooleanField(default=False)),
                ('timer_trigger', models.CharField(blank=True, choices=[('FY_START', 'FY_START'), ('FY_END', 'FY_END')], max_length=16, null=True)),
                ('timer_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='industry_types.industrytype')),
            ],
            options={
                'db_table': 'industry_fields',
                'unique_together': {('industry_type', 'field_key')},
            },
        ),
    ]
