# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.FloatField()),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('MATERIAL', 'MATERIAL'), ('PART', 'PART'), ('PRODUCT', 'PRODUCT')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='competitions.competition')),
            ],
            options={
                'db_table': 'warehouses',
                'indexes': [models.Index(fields=['competition', 'updated_at'], name='warehouses_competi_e4d0c7_idx')],
                'unique_together': {('competition', 'name')},
            },
        ),
    ]
