# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_alter_warehouse_capacity_alter_warehouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(
                choices=[
                    ('MATERIAL', 'MATERIAL'),
                    ('PART', 'PART'),
                    ('PRODUCT', 'PRODUCT'),
                    ('FUEL', 'FUEL'),
                ],
                max_length=16,
            ),
        ),
    ]
