# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('footprint', models.FloatField()),
                ('employment_rate_bonus', models.FloatField(default=0)),
                ('population_bonus', models.FloatField(default=0)),
                ('high_quality_population_bonus', models.FloatField(default=0)),
                ('price', models.FloatField()),
                ('happiness_index_bonus', models.FloatField(default=0)),
                ('per_capita_income_bonus', models.FloatField(default=0)),
                ('carbon_reduction_bonus', models.FloatField(default=0)),
                ('activation_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='competitions.competition')),
            ],
            options={
                'db_table': 'infrastructures',
                'indexes': [models.Index(fields=['competition', 'updated_at'], name='infrastruct_competi_6e285e_idx')],
                'unique_together': {('competition', 'name')},
            },
        ),
    ]
