# Generated by Django 5.0.14 on 2026-09-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0002_alter_infrastructure_activation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='activation_price',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
    ]
