# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('tech_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttechrequirement',
            name='tech_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requirements', to='tech_tree.technode'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['competition', 'updated_at'], name='parts_competi_97058b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='partmaterial',
            unique_together={('part', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='parttechrequirement',
            unique_together={('part', 'tech_node')},
        ),
    ]
