# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('party_count', models.IntegerField(default=2)),
                ('party_roles', models.TextField(default='[]')),
                ('input_schema', models.TextField(default='[]')),
                ('effects', models.TextField(default='[]')),
                ('conditions', models.TextField(default='[]')),
                ('graph', models.TextField(blank=True, null=True)),
                ('schema_version', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract_types',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING_EXEC', 'PENDING_EXEC'), ('EXECUTED', 'EXECUTED'), ('TERMINATED', 'TERMINATED')], default='DRAFT', max_length=16)),
                ('parties', models.TextField(default='[]')),
                ('inputs', models.TextField(default='{}')),
                ('execution_log', models.TextField(blank=True, null=True)),
                ('execution_result', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='competitions.competition')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='contracts.contracttype')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractFieldEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('industry_field_id', models.IntegerField()),
                ('field_key', models.CharField(max_length=128)),
                ('field_name', models.CharField(max_length=255)),
                ('op', models.CharField(choices=[('ADD', 'ADD'), ('SUB', 'SUB'), ('SET', 'SET')], max_length=8)),
                ('value_raw', models.TextField()),
                ('before_raw', models.TextField()),
                ('after_raw', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_effects', to='contracts.contract')),
            ],
            options={
                'db_table': 'contract_field_effects',
                'indexes': [models.Index(fields=['contract'], name='contract_fi_contrac_815d08_idx'), models.Index(fields=['company_id', 'industry_field_id'], name='contract_fi_company_922c0e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['competition', 'updated_at'], name='contracts_competi_5418c4_idx'),
        ),
    ]
