# Generated by Django 5.0.6 on 2026-08-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tech_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttechrequirement',
            name='tech_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requirements', to='tech_tree.technode'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['competition', 'updated_at'], name='products_competi_aa8172_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productpart',
            unique_together={('product', 'part')},
        ),
        migrations.AlterUniqueTogether(
            name='producttechrequirement',
            unique_together={('product', 'tech_node')},
        ),
    ]
